name: Build Status
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@master
            - name: Set up Node.js
              uses: actions/setup-node@master
              with:
                  node-version: 20.x

            - name: Install NPM dependencies
              run: npm ci

            - name: Get Coverage for badge
              run: |
                  SUMMARY="$(npm run test:coverage -- --coverageReporters='text-summary' | tail -2 | head -1)"
                  TOKENS=($SUMMARY)
                  echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
                  REF=${{ github.ref }}
                  echo "github.ref: $REF"
                  IFS='/' read -ra PATHS <<< "$REF"
                  BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
                  echo $BRANCH_NAME
                  echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
            - name: Create the Badge
              uses: schneegans/dynamic-badges-action@master
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  gistID: ${{ secrets.GIST_ID }}
                  filename: blog__${{ env.BRANCH }}.json
                  label: Test Coverage
                  message: ${{ env.COVERAGE }}
                  color: green
                  namedLogo: jest
